USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA MONEY_TRANSFER_DW.ANALYTICS;

CREATE TABLE IF NOT EXISTS FACT_TRANSACTIONS (
  TRANSACTION_KEY  NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
  TRANSACTION_ID   VARCHAR(64)   NOT NULL UNIQUE,
  ACCOUNT_FROM_KEY VARCHAR(255),
  ACCOUNT_TO_KEY   VARCHAR(255),
  DATE_KEY         NUMBER(38,0)  NOT NULL,
  AMOUNT           NUMBER(19,4),
  CURRENCY         VARCHAR(3)    NOT NULL,
  STATUS           VARCHAR(50),
  TRANSACTION_TYPE VARCHAR(50)   NOT NULL,
  DESCRIPTION      VARCHAR(500),
  REFERENCE_NUMBER VARCHAR(100),
  CREATED_ON       TIMESTAMP_NTZ(6),
  FAILURE_REASON   VARCHAR(255),
  IDEMPOTENCY_KEY  VARCHAR(255)  NOT NULL UNIQUE,
  REMARKS          VARCHAR(255),
  LOAD_DATE        TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);